### ISSUE TITLE
Add numbers to the tutorials

### ISSUE THREAD

**Issue by sloede** [trixi-framework/TrixiTutorials#1]
That way users can easily reference them by saying "tutorial 2 does not work" or "I don't understand the last part of tutorial 3"

**Comment by bennibolm** [comment]
Do you think about something like that?
![grafik](https://user-images.githubusercontent.com/74359358/126480835-5e531908-14a8-4304-b6e0-856aca699ced.png)
and
![grafik](https://user-images.githubusercontent.com/74359358/126481040-ab982936-8709-4f4e-ba2e-3ee0b13cf5b8.png)

**Comment by sloede** [comment]
I like the `Tutorial 1: Adding a new equation`. However, in the navbar, maybe it would be sufficient to just use `1 Adding a new equation`?

**Comment by sloede** [comment]
Also, maybe rename `Home` to something like `Introduction` to be more descriptive?

**Comment by bennibolm** [comment]
Yes, that looks better. If there are two tutorials about one topic (like in Trixi right now), it looks like that 
![grafik](https://user-images.githubusercontent.com/74359358/126484586-9d78453c-1e05-45c6-9225-ba84bde481db.png)

**Comment by sloede** [comment]
Yeah, let's use that!
