### ISSUE TITLE
Fix "Edit on GitHub" links

### ISSUE THREAD

**Issue by sloede** [trixi-framework/TrixiTutorials#3]
Right now, the `Edit on GitHub` links always lead to 404 - Page not found errors. They should point to the correct sources or disabled. Since the underlying `md` file is auto-generated, maybe we can just have them link to the original `.jl` files?

**Comment by bennibolm** [comment]
I fixed it such that the link is now directly to the `.jl` file.

**Comment by sloede** [comment]
Great, thanks!
