### ISSUE TITLE
Do not store output of notebooks

### ISSUE THREAD

**Issue by sloede** [trixi-framework/TrixiTutorials#5]
Right now, the notebooks (or at least the one for the first tutorial) also stores the output of executed cells:
![image](https://user-images.githubusercontent.com/3637659/126738860-c0117e9b-0e6d-45e9-a189-b9a9e9164093.png)

Is there a way to disable this such that only the input cells (i.e., without output) are stored?

**Comment by ranocha** [comment]
If you want to do this locally, I recommend https://github.com/kynan/nbstripout.

**Comment by sloede** [comment]
Thanks for this information! I think there should be an option in `Literate.jl` to do this, since the entire generation process happens on GH Actions, but I might be mistaken and we will need to fall back on something as you suggested.

**Comment by bennibolm** [comment]
Since the files are not executed for the notebooks anymore, no output cells are stored.
